Fix salesforce-update-sink.kamelet
Fix https://github.com/apache/camel-kamelets/issues/1590

At runtime the bean is renamed which seems to cause the
NoSuchEndpointException: No endpoint could be found for: local-salesforce-1